title: Mengzhen Zhang
logo:
description: On my academic experience
show_downloads:
google_analytics:
remote_theme: pages-themes/primer@v0.6.0
plugins:
- jekyll-remote-theme
header_pages:
- index.html
